### ISSUE TITLE
fmtlib's author again is very wrong again.

### ISSUE THREAD

**Issue by expnkx** [expnkx/fast_io#13]
I do not use twitter since I do not need it. However, someone privately told me fmtlib's author complained about my library again and again.

std::locale is very bad since it is not thread-safe and bloats binary size. The standard never guarantees std::locale to be thread-safe. It is thread-safe just for its reference-counting. Not your formatting options with locale. That is a common misunderstanding of C++ std::locale.
Just defining a std::locale object would add 800kb binary size to every program. (You can prove it with static linking). That is also why fmtlib is extremely bloated. Eliminating dead virtual functions is a really hard problem. GCC used to have that option and it was removed.
A lot of platform does not correctly support locale.
It creates an attack surface for ROP. That violates the zero-overhead principle. You can do much better without it.
https://github.com/expnkx/fast_io/blob/master/examples/0024.locale/lcv.cc
For example, this will never create any binary bloat.
BTW, the decimal point problem was NEVER a problem. https://github.com/expnkx/fast_io/blob/master/examples/0003.floating_point/comma.cc
![image](https://user-images.githubusercontent.com/57303909/85715137-1d991c80-b6b9-11ea-84ef-47d515eee9c0.png)

![image](https://user-images.githubusercontent.com/57303909/85715419-710b6a80-b6b9-11ea-94d5-8cf923c6856c.png)

About issue 10, did I say anything wrong? Of course not.
https://github.com/expnkx/fast_io/issues/10

![image](https://user-images.githubusercontent.com/57303909/85716008-0575cd00-b6ba-11ea-952b-43ae39bf9fa0.png)

This is not for performance reasons. It is for abstraction reasons. I need to provide people the same APIs for manipulating different I/O devices.

Recreate a wheel is never an option since it easily causes more UBs and CVEs than the already existing ones. No one wants another more string type. QString, MFCString, FString, string_view. What more string types do you want? I would argue it was the standard's fault to add the private keyword to C++ since it screws up everything.

If think you think it is merely for performance reasons, then why did I also do the hacks to C FILE and C++ filebuf? Why do I hack to get the FILE* from filebuf? I have said very clearly in the repo I did hacks.

https://github.com/expnkx/fast_io/tree/master/include/fast_io_legacy_impl/c
https://github.com/expnkx/fast_io/tree/master/include/fast_io_legacy_impl/cpp
https://github.com/expnkx/fast_io/tree/master/include/fast_io_legacy_impl/cpp/fp_hack

If you think it is not good. Feel free to provide me a bug-free solution.

This is another proof I said private and protected screws things up. OOP is objectively bad in general since it slows down performance.
https://www.ginac.de/~kreckel/fileno/

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/85720127-22ac9a80-b6be-11ea-87b8-7f87dead0872.png)

Clearly the author of fmt does not understand what inline is doing. inline is not just a hint for inlining functions.

**inline is more to prevent ODR violations**. If you do not write inline functions. The compiler will generate dead code even you are not using them. Not writing inline if you are not supposed to export them in the translation unit is de facto nonsense.

https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-quach.pdf

This security paper talked about 
![image](https://user-images.githubusercontent.com/57303909/85720620-99e22e80-b6be-11ea-9d5a-174f216b4d9c.png)

https://godbolt.org/z/VBfwYe
![image](https://user-images.githubusercontent.com/57303909/85720849-ceee8100-b6be-11ea-9c2d-469645d60185.png)
You can see functions without marking inline will generate dead functions that cause binary bloat.

**Comment by FrankHB** [comment]
There is at least one fact: `std::locale` is indeed not *that* bad, because you can always just have `std::locale` plus something else shitty, e.g. `std::locale` + C locale. And this is arguably more often.

The root of the evil is that the languages have specified the so-called locale-specific behavior in the core, thus nobody can wiped it out on demand, conceptionally. Every time you want to resolve such behavior with interoperations to the old-day craps you have already lost severely. The only way to workaround is to be (pretending to) locale-neutral - that is, ignore them totally. Do your right thing on a basis of minimal interface style (which is not necessarily under the name "locale").

Debating on how bad the stupid things is, unfortunately, equally stupid, if not more.

**Comment by expnkx** [comment]
> There is at least one fact: `std::locale` is indeed not _that_ bad, because you can always just have `std::locale` plus something else shitty, e.g. `std::locale` + C locale. And this is arguably more often.
> 
> The root of the evil is that the languages have specified the so-called locale-specific behavior in the core, thus nobody can wiped it out on demand, conceptionally. Every time you want to resolve such behavior with interoperations to the old-day craps you have already lost severely. The only way to workaround is to be (pretending to) locale-neutral - that is, ignore them totally. Do your right thing on a basis of minimal interface style (which is not necessarily under the name "locale").
> 
> Debating on how bad the stupid things is, unfortunately, equally stupid, if not more.

Unfortunately, you have people in the WG21 who would keep doing this. char8_t, char16_t, char32_t for examples instead of just forbidding any non-UTF8 encoding for char. This is completely ridiculous.

Of course, you should not expect them to do more harm than good, considering they've accepted all kinds of security vulnerabilities libraries like boost filesystem, charconv, format, networking into the standard library.

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/85740508-ad49c580-b6cf-11ea-8907-83ee8c17c994.png)
I found this to be too contradicting. They are saying preferring iostream for I/O and now promoting type-unsafe format string vulnerabilities like fmt. Prefer iostream for I/O and then ask you to disable sync with stdio. How to deal with thread-safety issues after you disable it?

**Comment by FrankHB** [comment]
> Unfortunately, you have people in the WG21 who would keep doing this. char8_t, char16_t, char32_t for examples instead of just forbidding any non-UTF8 encoding for char. This is completely ridiculous.
> 
Naive. I guess you can't even make UTF-EBCDIC out once there are IBM folks.

> Of course, you should not expect them to do more harm than good, considering they've accepted all kinds of security vulnerabilities libraries like boost filesystem, charconv, format, networking into the standard library.

Security is not a mission of the language, so there is nothing to do with them. Making almost everything complicated than needed to defeat the requirements of security as well as the no-overhead principle (which the language has been sold for decades), is certainly blamable, though.

**Comment by expnkx** [comment]
> > Unfortunately, you have people in the WG21 who would keep doing this. char8_t, char16_t, char32_t for examples instead of just forbidding any non-UTF8 encoding for char. This is completely ridiculous.
> 
> Naive. I guess you can't even make UTF-EBCDIC out once there are IBM folks.
> 
> > Of course, you should not expect them to do more harm than good, considering they've accepted all kinds of security vulnerabilities libraries like boost filesystem, charconv, format, networking into the standard library.
> 
> Security is not a mission of the language, so there is nothing to do with them. Making almost everything complicated than needed to defeat the requirements of security as well as the no-overhead principle (which the language has been sold for decades), is certainly blamable, though.

Of course, they have no goals right now. They would not even add a push_back_unchecked then ask why people recreate their own vector type.

I think hacking does less harm than all those political shit.

**Comment by FrankHB** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/57303909/85740508-ad49c580-b6cf-11ea-8907-83ee8c17c994.png)
> I found this to be too contradicting. They are saying preferring iostream for I/O and now promoting type-unsafe format string vulnerabilities like fmt. Prefer iostream for I/O and then ask you to disable sync with stdio. How to deal with thread-safety issues after you disable it?

Probably that means you have responsibilities to rule all uses of `stdio` out, to keep an eye on all I/O calls in the program, and to make sure every I/O you will do some synchronization completely (by global locking).

That is surely insane once you need things more than toy programs, i.e. the programs you will make sure no modules will do something unexpected, esp. `stdio` calls, **including any standard library implementions + "system" libraries you use**.

The faulty nature comes from the very early design of the whole environment. Instead local REPLs, many languages use implicit global resource ("streams") shared with the underlying implementations to provide the idiomatic I/O. Such standard I/O facilities are essentially not owned by the language runtime, so there exist no method to make your such assurance (unless you have control all the environment, which is usually freestanding).

**Comment by expnkx** [comment]
> Probably that means you have responsibilities to rule all uses of `stdio` out, to keep an eye on all I/O calls in the program, and to make sure every I/O you will do some synchronization completely (by global locking).

It is not possible to rule all uses of stdio out. Back in 1980s when iostream was designed, it was implemented with the POSIX file descriptor. Now every lazy fuck C++ standard library implementations (libstdc++, libc++ and msvc stl) use FILE* to implement fstream. They do not even give a shit to you for accessing FILE* of fstream because they cannot deal with the virtual inheritance of C++ fstream.

**Comment by expnkx** [comment]
> > I found this to be too contradicting. They are saying preferring iostream for I/O and now promoting type-unsafe format string vulnerabilities like fmt. Prefer iostream for I/O and then ask you to disable sync with stdio. How to deal with thread-safety issues after you disable it?
> 
> Probably that means you have responsibilities to rule all uses of `stdio` out, to keep an eye on all I/O calls in the program, and to make sure for every potentially racy I/O you will do some synchronization, completely (by global locking, for example).
> 
> That is surely insane once you need things more than toy programs, i.e. programs you will make sure no modules will do something unexpected, esp. `stdio` calls, **including any standard library implementions + "system" libraries you use**.
> 
> The faulty nature comes from the very early design of the whole environment. Instead of local REPLs, many languages use implicit global resources ("standard streams") shared with the underlying implementation to provide the idiomatic I/O by default. Such standard I/O facilities are essentially not owned by the language runtime, so there exist no method to make you such assurance (unless you have the control on all the environment, which is usually _freestanding_).

OH!! They are going to add locale for char8_t, char16_t, char32_t LOLOLOLOL.

They do not accept POSIX but they keep adding POSIX's shit into the language.

**Comment by FrankHB** [comment]
> > Probably that means you have responsibilities to rule all uses of `stdio` out, to keep an eye on all I/O calls in the program, and to make sure every I/O you will do some synchronization completely (by global locking).
> 
> It is not possible to rule all uses of stdio out. Back in 1980s when iostream was designed, it was implemented with the POSIX file descriptor. Now every lazy fuck C++ standard library implementations (libstdc++, libc++ and msvc stl) use FILE* to implement fstream. They do not even give a shit to you for accessing FILE* of fstream because they cannot deal with the virtual inheritance of C++ fstream.

Practically true, if you are using something must to be compatible with C or C++. False if you thrown all them away. Well, POSIX is Not-A-Thing without C compatibility..

> 
> Now they think "it is maybe for the time for you to access that shit" but they do not give how to construct a fstream with HANDLE or fd reversely which leads to TOCTTOU vulnerabilities completely unsolvable.
> http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1759r1.html
> This proposal is another shit since they will not provide you FILE* from fstream. It only provides you HANDLE. considering there are still many software built on file descriptors even on windows. This is complete nonsense.

TOCTTOU is more deep rooted in almost all contemporary filesystem and OS APIs, probably except NTFS TxF (which is deprecated by Microsoft for its complexity, lol). I am surprised there can be C++ userland API fixing the problem upon the unmodified system interface.

**Comment by expnkx** [comment]
> TOCTTOU is more deep rooted in almost all contemporary filesystem and OS APIs, probably except NTFS TxF (which is deprecated by Microsoft for its complexity, lol). I am surprised there can be C++ userland API fixing the problem upon the unmodified system interface.

Yes you can. The windows NT APIs provide all the POSIX semantics of filesystem. Including openat, accessat etc. It can even do transaction by yourself. NT filesystem is basically lock-free

**Comment by expnkx** [comment]
> Practically true, if you are using something must to be compatible with C or C++. False if you throw all them away. Well, POSIX is Not-A-Thing without C compatibility...
> 
> >

It is true only if you are using fast_io.

**Comment by FrankHB** [comment]
> 
> > TOCTTOU is more deep rooted in almost all contemporary filesystem and OS APIs, probably except NTFS TxF (which is deprecated by Microsoft for its complexity, lol). I am surprised there can be C++ userland API fixing the problem upon the unmodified system interface.
> 
> Yes you can. The windows NT APIs provide all the POSIX semantics of filesystem. Including openat, accessat etc. It can even do transaction by yourself. NT filesystem is basically lock-free

https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.83.8647

Well the system call interface has changed for that. However, `*at` call only work on a specific set of operations. This still does not resolve the problem of composability which requires a whole transaction mechanism.

> It is true only if you are using fast_io.

And *only* use it. No, you can't get rid of stdio, practically. (Even fast_io hacks for that.)

**Comment by expnkx** [comment]
> > > TOCTTOU is more deep rooted in almost all contemporary filesystem and OS APIs, probably except NTFS TxF (which is deprecated by Microsoft for its complexity, lol). I am surprised there can be C++ userland API fixing the problem upon the unmodified system interface.
> > 
> > 
> > Yes you can. The windows NT APIs provide all the POSIX semantics of filesystem. Including openat, accessat etc. It can even do transaction by yourself. NT filesystem is basically lock-free
> 
> https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.83.8647
> 
> Well the system call interface has changed for that. However, `*at` call only work on a specific set of operations. This still does not resolve the problem of composability which requires a whole transaction mechanism.
> 
> > It is true only if you are using fast_io.
> 
> And _only_ use it. No, you can't get rid of stdio, practically. (Even fast_io hacks for that.)

fast_io hacks stream too since none can be avoided in large scale code base. Even the freaking Rust language could not avoid them.

**Comment by expnkx** [comment]
I think fast_io finally goes in the correct direction. I can finally do https with fast_io while I could not do this with boost asio. It is clearly a lifesaver for me.

**Comment by FrankHB** [comment]
> 
> 
> > > > TOCTTOU is more deep rooted in almost all contemporary filesystem and OS APIs, probably except NTFS TxF (which is deprecated by Microsoft for its complexity, lol). I am surprised there can be C++ userland API fixing the problem upon the unmodified system interface.
> > > 
> > > 
> > > Yes you can. The windows NT APIs provide all the POSIX semantics of filesystem. Including openat, accessat etc. It can even do transaction by yourself. NT filesystem is basically lock-free
> > 
> > 
> > https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.83.8647
> > Well the system call interface has changed for that. However, `*at` call only work on a specific set of operations. This still does not resolve the problem of composability which requires a whole transaction mechanism.
> > > It is true only if you are using fast_io.
> > 
> > 
> > And _only_ use it. No, you can't get rid of stdio, practically. (Even fast_io hacks for that.)
> 
> fast_io hacks stream too since none can be avoided in large scale code base. Even the freaking Rust language could not avoid them.
> 

No, you can't hack the paths where stdio has been used directly by users, unless you *replace* the whole stdio implementation plus custom auditions on each call at runtime.
