### ISSUE TITLE
I will ban all fmt trolls from this project.

### ISSUE THREAD

**Issue by expnkx** [expnkx/fast_io#15]
fmt author blames my library for nonsense every day and now bans me on his twitter.

TBH, he has lost all his battles since all benchmarks prove I am perfectly right.
His entire Twitter is filled with people who have no idea about what is "inline" keyword means.
![image](https://user-images.githubusercontent.com/57303909/85948342-66054400-b91e-11ea-8dbb-0db4ac6838a6.png)

https://devblogs.microsoft.com/oldnewthing/20200521-00/?p=103777

The binary bloat of fmt is just completely ridiculous. His claim on constant bloat is also very wrong.
![image](https://user-images.githubusercontent.com/57303909/85948251-d5c6ff00-b91d-11ea-84f0-b4a1b29b2be5.png)

**Comment by olafurw** [comment]
I think you forgot to ban me.

**Comment by ViralTaco** [comment]
You can ban people on GitHub? Also… WTF am I doing here? (Oh yeah, I stared fast_io… FFS) Stop arguing, kids. (Or using bad operating systems [like Windows or anything from either IBM or Oracle]).
