### ISSUE TITLE
Your Hello World example vs common usage

### ISSUE THREAD

**Issue by Chess13234** [expnkx/fast_io#3]
You're using unbuffered writes;
 fwrite is faster than write in multiple small writes, because of buffering,
if you put print behind buffering, there is no extra syscalls("//bad 3 syscalls").
EXAMPLE: Inside a loop this will issue syscalls each iteration(this is a fairly common pattern):
```
for(int i=0;i<max;i++){
//code
print(something);
}
```

https://stackoverflow.com/questions/1360021/why-the-fwrite-libc-function-is-faster-than-the-syscall-write-function

**Comment by expnkx** [comment]
Hello. The problem of this fwrite approach is that it will break the atomicity of multiple processes which is why you often see data hazard on the console.
https://github.com/expnkx/fast_io/wiki/0001.-Hello-World

If you want a performance-related output to stdout, you can use
https://github.com/expnkx/fast_io/blob/master/include/fast_io.h


auto outbuf = fast_io::out_buf();
for(int i=0;i<max;i++){
//code
print(outbuf, something);
}

Do your test again.

**Comment by Chess13234** [comment]
Can something like buffered_print()/bprint()
be provided for users instead of initializing something like 'auto outbuf = fast_io::out_buf();' each time this is required? The use case for in-loop print is fairly common(e.g. printing arrays) and people will usually use the simplest approach(that is print()).

**Comment by expnkx** [comment]
> Can something like buffered_print()/bprint()
> be provided for users instead of initializing something like 'auto outbuf = fast_io::out_buf();' each time this is required? The use case for in-loop print is fairly common(e.g. printing arrays) and people will usually use the simplest approach(that is print()).

The issue here is that outbuf will waste more space. fast_io makes output buffer very large. Put something on the global makes the same mistake as iostream is making here. Now we have 3 inconsistent I/O global buffers. That is unfortunately a chaos.

You can just use

print(fast_io::c_stdout."Hello World"); to print it to stdout. If FILE* is doing buffered here, it will do buffer too, and it is consistent.

**Comment by expnkx** [comment]
> Can something like buffered_print()/bprint()
> be provided for users instead of initializing something like 'auto outbuf = fast_io::out_buf();' each time this is required? The use case for in-loop print is fairly common(e.g. printing arrays) and people will usually use the simplest approach(that is print()).

We have other concerns about putting buffer globally.

1. It will introduce dependency of libc malloc, which is not usable in a freestanding environment. If you are in a situation you do not have new get defined, you are serious trouble.
2. Binary bloat compared to assembly version of "Hello World".

**Comment by expnkx** [comment]
> Can something like buffered_print()/bprint()
> be provided for users instead of initializing something like 'auto outbuf = fast_io::out_buf();' each time this is required? The use case for in-loop print is fairly common(e.g. printing arrays) and people will usually use the simplest approach(that is print()).

BTW, AFAIK, even the C's stdout does not do buffer either.
The only non-synchronized stream would do this.

**Comment by Chess13234** [comment]
Could you add something like this
```
#define bprint(...) print(c_out,__VA_ARGS__)
```
This won't add any bloat.

**Comment by expnkx** [comment]
> Could you add something like this
> 
> ```
> #define bprint(...) print(c_out,__VA_ARGS__)
> ```
> 
> This won't add any bloat.

Then you have more macro pollutions. It will add bloat and introduce dependencies for example.

You can see neither stream has an elegant solution for this, that is why you see people abusing endl everywhere.

**Comment by expnkx** [comment]
> Could you add something like this
> 
> ```
> #define bprint(...) print(fast_io::c_stdout,__VA_ARGS__)
> ```
> 
> This won't add any bloat.

For console output, performance would never be good.

**Comment by Chess13234** [comment]
It might not be elegant, but it will be faster.
Unbuffered small writes are not a problem with libc printf()/puts(). When someone uses print()-like function he wouldn't suspect its unbuffered as most libraries provided buffered IO.

**Comment by expnkx** [comment]
> It might not be elegant, but it will be faster.
> Unbuffered small writes are not a problem with libc printf()/puts(). When someone uses print()-like function he wouldn't suspect its unbuffered as most libraries provided buffered IO.

Well, it is not as fast as defining an out_buf() object explicit since you do not have this issue at all.

If they see the performance issue, they will do same thing as you do and use out_buf(). It is also a process people learn the lessons among these basic stream concepts.

**Comment by expnkx** [comment]
> It might not be elegant, but it will be faster.
> Unbuffered small writes are not a problem with libc printf()/puts(). When someone uses print()-like function he wouldn't suspect its unbuffered as most libraries provided buffered IO.

global objects are all violations of zero-overhead principle to some degree. Using fast_io::out will force atomicity among different processes which are great.


Usually, for performance-centric I/O, you are doing it on obuf_file, not on global out.

**Comment by Chess13234** [comment]
fast_io::c_stdout is already provided by libc, there isn't any additional overhead(unless you somehow link without libc).

**Comment by expnkx** [comment]
> fast_io::c_stdout is already provided by libc, there isn't any additional overhead(unless you somehow link without libc).

That is exactly on design goal of this library which is to make it usable without libc or even without an operating system.

One issue is that C++ exceptions rely on stdio.h too. That is really frustrating for me.

**Comment by expnkx** [comment]
https://github.com/expnkx/fast_io/blob/master/testsuites/0005.freestanding/0001.Hello%20World/helloworld_linux.cc

**Comment by expnkx** [comment]
> fast_io::c_stdout is already provided by libc, there isn't any additional overhead(unless you somehow link without libc).

BTW, adding buffer to global out is not just to add a buffer, it will also add mutex, add tie to input which are exactly why LLVM bans iostream in the first place.

**Comment by expnkx** [comment]
> fast_io::c_stdout is already provided by libc, there isn't any additional overhead(unless you somehow link without libc).

However, fast_io::in owns a buffer since it is impossible to implement it without a buffer. Most issues I've seen come from input side, not output side.

**Comment by expnkx** [comment]
Ok. I have tested it. It looks libc implementations usually do not use buffer for console output and then add a buffer when you output to a file. In general, you can not even ensure its behavior.

![image](https://user-images.githubusercontent.com/57303909/82872496-20a9bd00-9f01-11ea-89c8-9ef1a8c31854.png)

**Comment by Chess13234** [comment]
stdout is line-buffered by default(though Microsoft doesn't respect standards).
If you printf("string ends with\n") the buffer is flushed.
https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin

**Comment by expnkx** [comment]
> stdout is line-buffered by default(though Microsoft doesn't respect standards).
> If you printf("string ends with\n") the buffer is flushed.
> https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin

Line buffer was a historical mistake. There is no point to use line buffer when you have tie.

![image](https://user-images.githubusercontent.com/57303909/82873457-89456980-9f02-11ea-8d21-46c839ccfbee.png)
I've tested the glibc stdout, it does not look like it does any kind of buffer here too.

**Comment by expnkx** [comment]
Ok I've seen your point. I will think about it more. Thank you.

**Comment by expnkx** [comment]
I think one solution to this issue is that to print data to c's stdout by default instead of printing to fast_io::out, However, I do not know whether I can detect we are using freestanding implementation. I will try this approach.

**Comment by expnkx** [comment]
@Chess13234 see whether it works now.
I would probably add another concept to deal with line buffer since if the libc itself does not do the correct thing we need some fallback.

**Comment by expnkx** [comment]
Unfortunately, I've seen performance gets worse since now fast_io treated FILE* as a buffer_output_stream on Windows, which is pretty bad since stdout may or may not contain a buffer.

**Comment by expnkx** [comment]
Add another concept to fall back to nonbuffer stream. libc sucks tbh.
