### ISSUE TITLE
添加BOM，用于MSVC编码识别

### ISSUE THREAD

**Issue by Akarinnnnn** [expnkx/fast_io#31]
rt，MSVC识别编码时优先选当前系统ANSI编码，导致简体中文Windows编译失败

**Comment by expnkx** [comment]
关于中文操作系统我很多都没有正确处理。一个问题就是GB18030转码我还没写。现在在重写整个输入。还有本地化的设施。

如果你有兴趣的话帮我写个sse的UTF8/UTF16/UTF32互转GB18030的代码。

**Comment by expnkx** [comment]
编译失败的原因能说一下么？我想看下

**Comment by expnkx** [comment]
如果是编译不过的话，话说msvc应该有finput-charset这种选项吧。直接写UTF-8就好了了。

**Comment by expnkx** [comment]
你不会是真的用cmake编译了吧。不用编译的。编译的是locale文件。不过也奇怪为何locale文件不能用。

**Comment by expnkx** [comment]
加我qq811452018。直接截图给我

**Comment by Akarinnnnn** [comment]
> 如果是编译不过的话，话说msvc应该有finput-charset这种选项吧。直接写UTF-8就好了了。
> 
> 说实话这套C的locale就是问题，动不动就出问题。fast_io本身就是为了解决这些问题的。

也确实是CMake编译locale的问题。编译器那边确实有/source-charset:utf8 /execution-charset:utf-8，但cmake把这个它给了msbuild导致实际的编译器收不到这个参数
很奇怪的一点，__declspec(dllexport)也报错
这是日志[输出-生成.txt](https://github.com/expnkx/fast_io/files/5756687/-.txt)

**Comment by expnkx** [comment]
> > 如果是编译不过的话，话说msvc应该有finput-charset这种选项吧。直接写UTF-8就好了了。
> > 说实话这套C的locale就是问题，动不动就出问题。fast_io本身就是为了解决这些问题的。
> 
> 也确实是CMake编译locale的问题。编译器那边确实有/source-charset:utf8 /execution-charset:utf-8，但cmake把这个它给了msbuild导致实际的编译器收不到这个参数
> 很奇怪的一点，__declspec(dllexport)也报错
> 这是日志[输出-生成.txt](https://github.com/expnkx/fast_io/files/5756687/-.txt)

 事实上就应该把execution-charset设置成GB18030.这里就是为的处理这个东西。

**Comment by expnkx** [comment]
你加一下我qq，我给你解释一下

**Comment by FrankHB** [comment]
这 smg ，issue 不就是用来解释的么。

从来不要指望 MSVC 对编码处理能健全到哪里去。另外 MSVC 的编辑器这里也会对你呵呵。

至于 BOM 本来就不是 wkrnd 而应该是个**文件**就自带的玩意儿。即便 C++ 对此明确睁一只眼闭一只眼，缺 BOM 之类的显式标记依赖私相授受的文件编码约定到处炸逻辑上就是明显活该。

**Comment by expnkx** [comment]
> 这 smg ，issue 不就是用来解释的么。
> 
> 从来不要指望 MSVC 对编码处理能健全到哪里去。另外 MSVC 的编辑器这里也会对你呵呵。
> 
> 至于 BOM 本来就不是 wkrnd 而应该是个**文件**就自带的玩意儿。即便 C++ 对此明确睁一只眼闭一只眼，缺 BOM 之类的显式标记依赖私相授受的文件编码约定到处炸逻辑上就是明显活该。

UTF-8文件有什么BOM，搞笑么?

**Comment by expnkx** [comment]
> 这 smg ，issue 不就是用来解释的么。
> 
> 从来不要指望 MSVC 对编码处理能健全到哪里去。另外 MSVC 的编辑器这里也会对你呵呵。
> 
> 至于 BOM 本来就不是 wkrnd 而应该是个**文件**就自带的玩意儿。即便 C++ 对此明确睁一只眼闭一只眼，缺 BOM 之类的显式标记依赖私相授受的文件编码约定到处炸逻辑上就是明显活该。

GCC等编译器根本就不支持BOM头。还加BOM呢呵呵，编码都不正确. UTF-8和UTF-8 BOM两种编码那是
