### ISSUE TITLE
Line scan doesn't compile

### ISSUE THREAD

**Issue by awson** [expnkx/fast_io#32]
Any example involving line scan doesn't compile on the latest `fast_io`.

Neither of gcc or latest (TRUNK) clang or latest (preview) msvc is able to compile it because of unsatisfied constraints in `scan_single_impl`.

Removing all the constraints from `scan_single_impl` gets it compiled by clang and gcc, but resulting executable crashes on Windows with various errors (e.g. C0000003 or C0000374).

MSVC still can't compile anything barfing that `scan_single_impl` "must return a value".

**Comment by expnkx** [comment]
sorry for the late reply since I was sleeping. Can you show me the code?

**Comment by expnkx** [comment]
1:
```cpp
#include"../../include/fast_io.h"

int main()
{
	using namespace fast_io::manipulators;
	for(std::string str;scan<true>(line_get(str));println(str));
}
```
2. line_generator
```cpp
#include"../../include/fast_io.h"

int main()
{
	for(auto line : line_generator(fast_io::c_stdin()))
		println(line);
}
```

also works

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/103805109-259b2700-5021-11eb-87ae-f77b68af9a3a.png)

**Comment by awson** [comment]
E.g., this simple code doesn't work for me (using `ast_io::ibuf_file` instead of ` fast_io::native_file` doesn't help)

```
#include <fast_io.h>
#include <fast_io_device.h>
#include <string>

int main()
{
  fast_io::native_file file("any_text_file", fast_io::open_mode::in);
  std::string str;
  scan<true>(file, fast_io::line(str));
  println(str);
}
```

**Comment by expnkx** [comment]
> E.g., this simple code doesn't work for me (using `ast_io::ibuf_file` instead of ` fast_io::native_file` doesn't help)
> 
> ```
> #include <fast_io.h>
> #include <fast_io_device.h>
> #include <string>
> 
> int main()
> {
>   fast_io::native_file file("any_text_file", fast_io::open_mode::in);
>   std::string str;
>   scan<true>(file, fast_io::line(str));
>   println(str);
> }
> ```
> 
> "any_text_file" is any reasonable text file.

No. it is 
```cpp
scan<true>(file,fast_io::manipulators::line_get(str));
```

**Comment by expnkx** [comment]
> E.g., this simple code doesn't work for me (using `ast_io::ibuf_file` instead of ` fast_io::native_file` doesn't help)
> 
> ```
> #include <fast_io.h>
> #include <fast_io_device.h>
> #include <string>
> 
> int main()
> {
>   fast_io::native_file file("any_text_file", fast_io::open_mode::in);
>   std::string str;
>   scan<true>(file, fast_io::line(str));
>   println(str);
> }
> ```
> 
> "any_text_file" is any reasonable text file.

btw, please do not use native_file for reading data. they do not contain buffers resulting in discarding of data and slowness.

**Comment by expnkx** [comment]
i think your issue should be solved. Close it
