### ISSUE TITLE
Hi, Can we fix the warning seriously

### ISSUE THREAD

**Issue by ouliuquan** [expnkx/fast_io#36]
Hi expnkx, when I use this I/O lib, just a print("Hello World!\n") example, it burns a lot warnings, this should not be happen.

If we want to compete with others, like fmt or std, we should clean up the warning first.

`已启动重新生成…
1>------ 已启动全部重新生成: 项目: ProjectStarter, 配置: Debug x64 ------
1>main.cpp
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\impl.h(19,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\impl.h(20): message : 查看对正在编译的 类 模板 实例化“fast_io::manip::scan_transmitter<Func,operation>”的引用
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(15,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(97): message : 查看对正在编译的 类 模板 实例化“fast_io::scan_iterator<input,Func>”的引用
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(23,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(24,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(129,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_transmit\scan_generator.h(153): message : 查看对正在编译的 类 模板 实例化“fast_io::scan_generator<input,Fun>”的引用
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_freestanding.h(27,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\scan_freestanding.h(102): message : 查看对正在编译的 类 模板 实例化“fast_io::unget_temp_buffer<T>”的引用
\ProjectStarter\include\fast_io\fast_io_core_impl\intrinsics.h(110,19): warning C4244: “初始化”: 从“uint64_t”转换到“uint32_t”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_core_impl\intrinsics.h(112,19): warning C4244: “初始化”: 从“uint64_t”转换到“uint32_t”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_core_impl\integers\sto\sto_overhual.h(404,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\integers\sto\sto_overhual.h(695): message : 查看对正在编译的 类 模板 实例化“fast_io::details::ctx_scan_integer::voldmort<base,contiguous_only,Iter,P,T>”的引用
\ProjectStarter\include\fast_io\fast_io_core_impl\integers\sto\sto_overhual.h(405,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_core_impl\integers\sto\sto_overhual.h(406,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\string\string_context.h(145,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\string\string_context.h(246): message : 查看对正在编译的 类 模板 实例化“fast_io::details::ctx_scan_line_get::voldmort<contiguous_only,dynamic_ch,T,Iter>”的引用
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\code_cvt\utf.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\floating_point\dragonbox\dragonbox.h(2710,3): warning C5030: 未识别属性“msvc::force_inline”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\floating_point\dragonbox\dragonbox.h(2710,3): warning C5223: 属性命名空间 "msvc" 中的所有属性名称均保留用于实现
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\floating_point\dragonbox\dragonbox.h(2975): message : 查看对正在编译的 类 模板 实例化“fast_io::jkj::dragonbox::detail::impl<Float>”的引用
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\iobuf.h(56,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\iobuf.h(109): message : 查看对正在编译的 类 模板 实例化“fast_io::basic_buf_handler<CharT,need_secure_clear,buffer_size,Allocator>”的引用
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\serialize.h(19,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\serialize.h(20): message : 查看对正在编译的 类 模板 实例化“fast_io::serializer<stm>”的引用
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\serialize.h(59,4): warning C4648: 已忽略标准特性“no_unique_address”
\ProjectStarter\include\fast_io\fast_io_freestanding_impl\serialize.h(60): message : 查看对正在编译的 类 模板 实例化“fast_io::deserializer<stm>”的引用
\ProjectStarter\include\fast_io\fast_io_hosted\platforms\nt_api.h(11,34): warning C5030: 未识别属性“gnu::may_alias”
\ProjectStarter\include\fast_io\fast_io_hosted\platforms\posix.h(427,27): warning C4267: “参数”: 从“size_t”转换到“unsigned int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_hosted\platforms\posix.h(474,53): warning C4267: “参数”: 从“size_t”转换到“uint32_t”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_hosted\platforms\posix.h(520,54): warning C4267: “参数”: 从“size_t”转换到“uint32_t”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_hosted\platforms\posix.h(523,53): warning C4267: “参数”: 从“size_t”转换到“uint32_t”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(138,42): warning C4244: “参数”: 从“__int64”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(175,42): warning C4244: “参数”: 从“__int64”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(208,88): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(244,88): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(279,53): warning C4244: “参数”: 从“__int64”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(315,53): warning C4244: “参数”: 从“__int64”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(350,90): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
\ProjectStarter\include\fast_io\fast_io_legacy_impl\c\universal_crt.h(386,90): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
\source\repos\ProjectStarter\x64\Debug\ProjectStarter.exe
1>已完成生成项目“ProjectStarter.vcxproj”的操作。
========== 全部重新生成: 成功 1 个，失败 0 个，跳过 0 个 ==========
`

**Comment by expnkx** [comment]
这样行了吧。
[[no_unique_address]]属性不支持纯粹是编译器自身的问题。编译器对C++20特性支持不完全。

**Comment by ouliuquan** [comment]
谢谢大神修复那么快，我明天测试看看，如果没问题了我就关闭掉这个Issue。我确实不知道是编译器的问题，抱歉。
有warning的库确实会给开发者带来很多困扰，会掩盖掉项目真正的warning。

还有一个不知道是不是算bug的问题，在Windows下面动态库后缀名应该是dll而不是so，目前好像cmake生成的是so

**Comment by expnkx** [comment]
> 还有一个不知道是不是算bug的问题，在Windows下面动态库后缀名应该是dll而不是so，目前好像cmake生成的是so

我就是生成.so的，根本就不影响。原因是cmake默认在cygwin或是msys2下它就成了.so，所以干脆全用.so作后缀名。用什么都行，根本就不影响。就像.txt文件你不写.txt，你写.tt也可以认为是文本文件一样

**Comment by ouliuquan** [comment]
如果二进制一样那当然不受影响，这种是细节。如果第一次用别人怎么知道你是写错了还是别的原因呢？显得不够专业。我认为在我们力所能及的地方做到最好，希望你的库能成为[https://github.com/nlohmann/json](url)那样的事实标准，不要落了这种细节。

**Comment by expnkx** [comment]
> 如果二进制一样那当然不受影响，这种是细节。如果第一次用别人怎么知道你是写错了还是别的原因呢？显得不够专业。我认为在我们力所能及的地方做到最好，希望你的库能成为[https://github.com/nlohmann/json](url)那样的事实标准，不要落了这种细节。

我控制不了cmake生成的后缀，就出问题，否则cmake在cygwin下它就是.so的。所以干脆全用.so作后缀名。
