### ISSUE TITLE
Can you give a simple compare with Libuv.

### ISSUE THREAD

**Issue by Heromyth** [expnkx/fast_io#6]
It seems fast_io does more than libuv. Is there somthing that libuv can do, but fast_io can't do?

**Comment by expnkx** [comment]
I never used libuv before. I just want fast_io to integrate all user-space I/O facilities since separate them have all kinds of integration issues. The goal is probably not the same here.

**Comment by expnkx** [comment]
For example, if you have your knowledge about how to print "Hello World" to screen, you should already have the knowledge of how to print "Hello World" to the network.

**Comment by expnkx** [comment]
The main goal is to replace stdio.h and iostream.

However, things like networking are doing exactly what stdio.h and iostream could do from operating system perspective. They all use POSIX file descriptors and for the operating system. A network socket is a file.

**Comment by expnkx** [comment]
BTW, the async part of fast_io is far from usable. Win32 IOCP only supports file, not socket. Linux io uring support has not started either. Unfortunately, the work is huge. I need time to finish all of them.

**Comment by magenbluten** [comment]
what about posix aio ( with native support on freebsd and in linux via libaio or custom syscalls like in <https://github.com/scylladb/seastar/blob/master/src/core/linux-aio.cc>, glibc aio is broken ). all of them need kind of `io-context`

for network stuff one needs to do binary encoding ( likewise with crypto ). i there a simple example on hot to do that writing in a say `stream<std::byte>` kind of thingy? ( honoring endianess ). but i guess encoding has to happen "externally" and then just commit the buffer? not sure how that would compose.

**Comment by expnkx** [comment]
> what about posix aio ( with native support on freebsd and in linux via libaio or custom syscalls like in https://github.com/scylladb/seastar/blob/master/src/core/linux-aio.cc, glibc aio is broken ). all of them need kind of `io-context`
> 
> for network stuff one needs to do binary encoding ( likewise with crypto ). i there a simple example on hot to do that writing in a say `stream<std::byte>` kind of thingy? ( honoring endianess ). but i guess encoding has to happen "externally" and then just commit the buffer? not sure how that would compose.
> 
> * [freebsd flavored / posix aio](https://www.freebsd.org/cgi/man.cgi?query=aio&sektion=4&manpath=freebsd-release-ports)
> * [ linux flavored / posix aio](https://www.man7.org/linux/man-pages/man7/aio.7.html)

Well. I think just support the latest IO uring and windows IOCP is enough.

**Comment by Heromyth** [comment]
Thanks for your reply. I got it. I need to wrap a network IO library for D. So the libuv is more suitable.

By the way, the POSIX AIO is really not good as it sounds. We are using epoll instead and maybe switch to the `uring` in the future.

**Comment by expnkx** [comment]
> Thanks for your reply. I got it. I need to wrap a network IO library for D. So the libuv is more suitable.
> 
> By the way, the POSIX AIO is really not good as it sounds. We are using epoll instead and maybe switch to the `uring` in the future.

TBH, if you do not care too much about async performance, you can just use the multiprocess async server in fast_io. It directly works on Linux.

https://github.com/expnkx/fast_io/blob/master/examples/0017.tcp_multiprocess_async/server.cc
https://github.com/expnkx/fast_io/blob/master/examples/0017.tcp_multiprocess_async/server_child_process.cc
