### ISSUE TITLE
C++ reddit is a fucking a dumb shit.

### ISSUE THREAD

**Issue by expnkx** [expnkx/fast_io#8]
https://www.reddit.com/r/cpp/comments/gtzsnm/we_need_to_do_better_than_cin_for_new_programmers/

This is a moron thread and the relies are even worse.

**"The serious reservation is this: I just never ever ever get input from the terminal in real world code. I get command line flags, I read data files, I literally never read from the terminal anymore.".** 

lol. Do they know stdin and stdout can be used for even networking? No, they do not. Do they understand what is a file descriptor? No, they don't.

https://github.com/expnkx/fast_io/blob/master/examples/0017.tcp_multiprocess_async/server.cc
https://github.com/expnkx/fast_io/blob/master/examples/0017.tcp_multiprocess_async/server_child_process.cc

These people are fucking retarded and they have no idea what they are talking about.

GAME DEVS ARE IN GENERAL MORONS. Think about how bad the current World Of Warcraft is.

Clearly, Linus was right:

**C++ is a horrible language. It's made more horrible by the fact that a lot of substandard programmers use it, to the point where it's much much easier to generate total and utter crap with it.**

Of course, these OOP "C with Classes" losers will continue abusing std::unique_ptr for their stupid GUI for "I/O" without understanding any basic things about the operating system. std::unique_ptr considered harmful. It is just as bad as raw pointers since it only encourages stupid C with Classes dumb shit in the real world code base. They deserve to be suffered from resources leaking for their stupid OOP designs.

Yes to **C with Concepts**. No to **C with Classes**.

**Comment by grober82** [comment]
Why was this issue closed? It is still not fixed.
