### ISSUE TITLE
Target specific option mismatch.

### ISSUE THREAD

**Issue by solarprime** [expnkx/fast_io#9]
Getting a string of errors when attempting to compile the hashing examples:

```g++ -o hello_hmac_sha256 hello_hmac_sha256.cc -std=c++20 -O3 -march=native```

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:103,
                 from ../../include/fast_io_freestanding_impl/code_cvt/utf.h:6,
                 from ../../include/fast_io_freestanding.h:23,
                 from ../../include/fast_io_hosted.h:9,
                 from ../../include/fast_io.h:3,
                 from hello_hmac_sha256.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/10/include/shaintrin.h: In member function 'void fast_io::sha256_function::operator()(std::span<unsigned int, 8>, std::span<const std::byte, 64>)':
/usr/lib/gcc/x86_64-linux-gnu/10/include/shaintrin.h:87:1: error: inlining failed in call to 'always_inline' '__m128i _mm_sha256rnds2_epu32(__m128i, __m128i, __m128i)': target specific option mismatch
   87 | _mm_sha256rnds2_epu32 (__m128i __A, __m128i __B, __m128i __C)
```
Currently on gcc 10.0.1.  Removing `-march=native` compiles without issue, but the SIMD instructions aren't used.

```
processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
stepping	: 10
microcode	: 0xd6
cpu MHz		: 800.009
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 5
cpu cores	: 6
apicid		: 11
initial apicid	: 11
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
bogomips	: 7399.70
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:```

**Comment by expnkx** [comment]
> Getting a string of errors when attempting to compile the hashing examples:
> 
> `g++ -o hello_hmac_sha256 hello_hmac_sha256.cc -std=c++20 -O3 -march=native`
> 
> ```
> In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:103,
>                  from ../../include/fast_io_freestanding_impl/code_cvt/utf.h:6,
>                  from ../../include/fast_io_freestanding.h:23,
>                  from ../../include/fast_io_hosted.h:9,
>                  from ../../include/fast_io.h:3,
>                  from hello_hmac_sha256.cc:1:
> /usr/lib/gcc/x86_64-linux-gnu/10/include/shaintrin.h: In member function 'void fast_io::sha256_function::operator()(std::span<unsigned int, 8>, std::span<const std::byte, 64>)':
> /usr/lib/gcc/x86_64-linux-gnu/10/include/shaintrin.h:87:1: error: inlining failed in call to 'always_inline' '__m128i _mm_sha256rnds2_epu32(__m128i, __m128i, __m128i)': target specific option mismatch
>    87 | _mm_sha256rnds2_epu32 (__m128i __A, __m128i __B, __m128i __C)
> ```
> 
> Currently on gcc 10.0.1. Removing `-march=native` compiles without issue, but the SIMD instructions aren't used.
> 
> ```
> processor	: 11
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 158
> model name	: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
> stepping	: 10
> microcode	: 0xd6
> cpu MHz		: 800.009
> cache size	: 12288 KB
> physical id	: 0
> siblings	: 12
> core id		: 5
> cpu cores	: 6
> apicid		: 11
> initial apicid	: 11
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 22
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
> bogomips	: 7399.70
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 39 bits physical, 48 bits virtual
> power management:```
> ```

You need to pass -maes -msse4.2 -msha for using them.

**Comment by solarprime** [comment]
Just figured that out, lol.  Thanks.

**Comment by solarprime** [comment]
This does not compile with `-march=native` on processors that don't have the SHA intrinsics (e.g. 8700K).  Passing `-msha` will allow compilation, but obviously the binary will not be able to run.  Guarding code using sha intrinsics with `#ifdef __SSE__` or `#ifdef __SSE4_X__` is incorrect.

**Comment by expnkx** [comment]
> This does not compile with `-march=native` on processors that don't have the SHA intrinsics (e.g. 8700K). Passing `-msha` will allow compilation, but obviously the binary will not be able to run. Guarding code using sha intrinsics with `#ifdef __SSE__` or `#ifdef __SSE4_X__` is incorrect.

So you want the code to be guarded with cpuid at runtime?

**Comment by solarprime** [comment]
No, I think guarding with something like `__SHA__` but I'm not sure what the correct macro is.

**Comment by solarprime** [comment]
[This SO article](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.

**Comment by expnkx** [comment]
> [This SO post](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.

I think just guard code with SHA is not enough. It needs to be both guarded with sha and sse

**Comment by solarprime** [comment]
> > [This SO post](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.
> 
> I think just guard code with SHA is not enough. It needs to be both guarded with sha and sse

Agreed.

**Comment by expnkx** [comment]
> > > [This SO post](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.
> > 
> > 
> > I think just guard code with SHA is not enough. It needs to be both guarded with sha and sse
> 
> Agreed.

I think it should get fixed now.

**Comment by expnkx** [comment]
> > > [This SO post](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.
> > 
> > 
> > I think just guard code with SHA is not enough. It needs to be both guarded with sha and sse
> 
> Agreed.

I think for your CPU, you can use sha256 openssl or sha256 cryptopp for higher throughput. My implementations are still very naive and only work fast with CPUs with sha instructions.

https://github.com/expnkx/fast_io/blob/master/examples/0028.openssl/hash/sha256_openssl.cc
https://github.com/expnkx/fast_io/blob/master/examples/0053.cryptopp/sha256_cryptopp.cc

**Comment by solarprime** [comment]
> > > > [This SO post](https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic) seems to suggest that `__SHA__` might be the correct define to guard with.
> > > 
> > > 
> > > I think just guard code with SHA is not enough. It needs to be both guarded with sha and sse
> > 
> > 
> > Agreed.
> 
> I think for your CPU, you can use sha256 openssl or sha256 cryptopp for higher throughput. My implementations are still very naive and only work fast with CPUs with sha instructions.
> 
> https://github.com/expnkx/fast_io/blob/master/examples/0028.openssl/hash/sha256_openssl.cc
> https://github.com/expnkx/fast_io/blob/master/examples/0053.cryptopp/sha256_cryptopp.cc

Thanks.  My dev machine doesn't have sha instructions, but production machines will.

**Comment by solarprime** [comment]
The fix allows compilation.  Thanks for the quick responses.
